language: go
dist: trusty
sudo: false
go:
  - 1.11.x
  - 1.12.x
env:
  - GO111MODULE=on
install:
  - go mod verify
  - go mod vendor
script:
  - go test -race -cover -v `go list ./... | grep -v 'vendor'`
