apiVersion: v2
home: https://github.com/bryk-io/did-method
name: didctl
description: A Helm chart for Kubernetes
type: application
version: 0.2.0
appVersion: 0.2.0
maintainers:
  - name: Ben Cessa
    email: ben@pixative.com
keywords:
  - bryk
  - did