agent:
  pow: 24
  tls:
    enabled: false
    secret: "tls-secret-name-goes-here"
  storage:
    enabled: true
    size: "1Gi"
    className: "default"

nameOverride: ""
fullnameOverride: ""
replicaCount: 1
restartPolicy: Always
imagePullSecrets: []

image:
  repository: registry.bryk.io/base/didctl
  pullPolicy: IfNotPresent

serviceAccount:
  create: false
  name:

service:
  type: ClusterIP
  port: 9090

ingress:
  enabled: false
  annotations: {}
#    kubernetes.io/ingress.class: "nginx"
#    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  hosts: []
#    - host: chart-example.local
#      paths:
#        - "/"
  tls: []
#    - secretName: chart-example-tls
#      hosts:
#        - chart-example.local

podSecurityContext: {}

securityContext: {}
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  # capabilities:
  #   drop:
  #   - ALL

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
