apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "didctl.fullname" . }}
  labels:
    {{- include "didctl.labels" . | nindent 4 }}
data:
  config.yaml: |-
  {{- toYaml .Values.configuration | nindent 4 }}
