{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "didctl.serviceAccountName" . }}
  labels:
{{ include "didctl.labels" . | nindent 4 }}
{{- end -}}
